name: 'Sonatype Lifecycle GitHub Action'
author: 'Sonatype Community'
description: 'Run a Sonatype Lifecycle policy evaluation as part of your GitHub Actions workflow.'
inputs:
  serverUrl:
    description: 'Sonatype Lifecycle Server URL'
    required: true
  username:
    description: 'Username to connect to Sonatype Lifecycle Server for policy evaluation'
    required: true
  password:
    description: 'Password to connect to Sonatype Lifecycle Server for policy evaluation'
    required: true
  applicationId:
    description: 'Determines the policy elements (policies, labels, and license threat groups) to associate with this build, and is managed via the Sonatype Lifecycle Server.'
    required: true
  stage:
    description: 'Controls the stage the policy evaluation will be run against on the Sonatype Lifecycle Server.'
    required: true
    default: 'Build'
  target:
    description: 'This is the path to a specific application archive file, a directory containing such archives or the ID of a Docker image. For archives, a number of formats are supported, including jar, war, ear, tar, tar.gz, zip and many others.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.serverUrl }}
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.applicationId }}
    - ${{ inputs.stage }}
    - ${{ inputs.target }}
branding:
  icon: 'shield'
  color: 'gray-dark'