name: 'Release Action'

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        name: 'Release Action'
        runs-on: ubuntu-latest

        steps:
            - name: Update CHANGELOG
              id: changelog
              uses: requarks/changelog-action@v1
              with:
                  token: ${{ secrets.github_token }}
                  tag: ${{ github.ref_name }}
                  writeToFile:

            - name: Create Release
              uses: mikepenz/action-gh-release@v0.6.0
              with:
                  body: ${{ steps.changelog.outputs.changes }}
